const products = [
  {
    _id:: 1,
    name: "Women Round Neck Cotton Top",
    description:
      "Comfortable cotton top with a round neck design, perfect for casual wear.",
    price: 100,
    image: ["image1.jpg"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    date: "12-11-2024",
    bestSeller: true
  },
  {
    _id:: 2,
    name: "Men's Casual T-Shirt",
    description: "Soft and stylish T-shirt for everyday casual look.",
    price: 150,
    image: ["image2.jpg"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    date: "10-11-2024",
    bestSeller: false
  },
  {
    _id:: 3,
    name: "Unisex Jogger Pants",
    description: "Relaxed-fit joggers for comfort and style.",
    price: 200,
    image: ["image3.jpg"],
    category: "Unisex",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    date: "05-11-2024",
    bestSeller: true
  },
  {
    _id:: 4,
    name: "Men's Denim Jacket",
    description: "Classic denim jacket with a contemporary twist.",
    price: 250,
    image: ["image4.jpg"],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L"],
    date: "07-11-2024",
    bestSeller: false
  },
  {
    _id:: 5,
    name: "Women's Flare Skirt",
    description: "Elegant flare skirt for a chic look.",
    price: 180,
    image: ["image5.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M"],
    date: "15-11-2024",
    bestSeller: true
  },
  {
    _id:: 6,
    name: "Women's Hoodie",
    description: "Cozy and stylish hoodie for cold weather.",
    price: 220,
    image: ["image6.jpg"],
    category: "Women",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "18-11-2024",
    bestSeller: false
  },
  {
    _id:: 7,
    name: "Men's Slim Fit Chinos",
    description:
      "Comfortable slim fit chinos perfect for work or casual outings.",
    price: 190,
    image: ["image7.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    date: "20-11-2024",
    bestSeller: false
  },
  {
    _id:: 8,
    name: "Unisex Crewneck Sweatshirt",
    description: "Warm and comfortable crewneck sweatshirt.",
    price: 160,
    image: ["image8.jpg"],
    category: "Unisex",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    date: "12-11-2024",
    bestSeller: true
  },
  {
    _id:: 9,
    name: "Women's Ankle Length Leggings",
    description: "Stretchable and durable leggings for yoga and workout.",
    price: 130,
    image: ["image9.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "10-11-2024",
    bestSeller: true
  },
  {
    _id:: 10,
    name: "Men's Full-Zip Hoodie",
    description: "Stylish full-zip hoodie for casual wear.",
    price: 210,
    image: ["image10.jpg"],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "25-11-2024",
    bestSeller: false
  },
  {
    _id:: 11,
    name: "Women's Summer Dress",
    description: "Lightweight summer dress perfect for warm weather.",
    price: 300,
    image: ["image11.jpg"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "22-11-2024",
    bestSeller: true
  },
  {
    _id:: 12,
    name: "Men's Polo Shirt",
    description: "Classic polo shirt for formal and casual settings.",
    price: 120,
    image: ["image12.jpg"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    date: "12-11-2024",
    bestSeller: true
  },
  {
    _id:: 13,
    name: "Women's Casual Trousers",
    description: "Loose-fit casual trousers for a comfortable day out.",
    price: 180,
    image: ["image13.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    date: "13-11-2024",
    bestSeller: true
  },
  {
    _id:: 14,
    name: "Men's Athletic Shorts",
    description:
      "Breathable and comfortable shorts for exercise and casual wear.",
    price: 90,
    image: ["image14.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "17-11-2024",
    bestSeller: false
  },
  {
    _id:: 15,
    name: "Unisex Rain Jacket",
    description: "Waterproof jacket suitable for rainy weather.",
    price: 250,
    image: ["image15.jpg"],
    category: "Unisex",
    subCategory: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    date: "12-11-2024",
    bestSeller: true
  },
  {
    _id:: 16,
    name: "Women's Long Sleeve Shirt",
    description: "Stylish long sleeve shirt for casual or formal wear.",
    price: 170,
    image: ["image16.jpg"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    date: "21-11-2024",
    bestSeller: false
  },
  {
    _id:: 17,
    name: "Men's Leather Belt",
    description: "Durable leather belt to complement your outfit.",
    price: 80,
    image: ["image17.jpg"],
    category: "Men",
    subCategory: "Accessories",
    sizes: ["M", "L"],
    date: "14-11-2024",
    bestSeller: true
  },
  {
    _id:: 18,
    name: "Women's Sports Bra",
    description: "Supportive and comfortable sports bra for activewear.",
    price: 120,
    image: ["image18.jpg"],
    category: "Women",
    subCategory: "Innerwear",
    sizes: ["S", "M", "L"],
    date: "12-11-2024",
    bestSeller: false
  },
  {
    _id:: 19,
    name: "Men's Tracksuit",
    description: "Full tracksuit for athletic or casual wear.",
    price: 260,
    image: ["image19.jpg"],
    category: "Men",
    subCategory: "Activewear",
    sizes: ["M", "L", "XL"],
    date: "20-11-2024",
    bestSeller: true
  },
  {
    _id:: 20,
    name: "Women's Skinny Jeans",
    description: "Stretchable skinny jeans for a sleek look.",
    price: 220,
    image: ["image20.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "16-11-2024",
    bestSeller: false
  },
  {
    _id:: 21,
    name: "Men's Button-Up Shirt",
    description: "Crisp button-up shirt for formal occasions.",
    price: 190,
    image: ["image21.jpg"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    date: "18-11-2024",
    bestSeller: false
  },
  {
    _id:: 22,
    name: "Women's Workout Leggings",
    description: "High-performance leggings for workouts and yoga.",
    price: 150,
    image: ["image22.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "19-11-2024",
    bestSeller: true
  },
  {
    _id:: 23,
    name: "Men's Winter Jacket",
    description: "Warm and stylish jacket for cold weather.",
    price: 350,
    image: ["image23.jpg"],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "22-11-2024",
    bestSeller: true
  },
  {
    _id:: 24,
    name: "Women's Fleece Jacket",
    description: "Cozy fleece jacket for a casual and warm layer.",
    price: 230,
    image: ["image24.jpg"],
    category: "Women",
    subCategory: "Outerwear",
    sizes: ["S", "M", "L"],
    date: "23-11-2024",
    bestSeller: false
  },
  {
    _id:: 25,
    name: "Men's Cargo Pants",
    description: "Durable and functional cargo pants with multiple pockets.",
    price: 180,
    image: ["image25.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "24-11-2024",
    bestSeller: false
  },
  {
    _id:: 26,
    name: "Women's Leather Gloves",
    description: "Premium leather gloves for a stylish winter accessory.",
    price: 100,
    image: ["image26.jpg"],
    category: "Women",
    subCategory: "Accessories",
    sizes: ["S", "M"],
    date: "25-11-2024",
    bestSeller: true
  },
  {
    _id:: 27,
    name: "Men's Knitted Scarf",
    description: "Warm knitted scarf for a cozy winter look.",
    price: 70,
    image: ["image27.jpg"],
    category: "Men",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "12-11-2024",
    bestSeller: false
  },
  {
    _id:: 28,
    name: "Women's Maxi Dress",
    description: "Flowing maxi dress perfect for formal events.",
    price: 320,
    image: ["image28.jpg"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "28-11-2024",
    bestSeller: true
  },
  {
    _id:: 29,
    name: "Men's Classic Suit",
    description: "Elegant and formal suit for special occasions.",
    price: 550,
    image: ["image29.jpg"],
    category: "Men",
    subCategory: "Formalwear",
    sizes: ["M", "L", "XL"],
    date: "30-11-2024",
    bestSeller: false
  },
  {
    _id:: 30,
    name: "Women's Wool Coat",
    description: "Classic wool coat for stylish winter wear.",
    price: 400,
    image: ["image30.jpg"],
    category: "Women",
    subCategory: "Outerwear",
    sizes: ["M", "L"],
    date: "01-12-2024",
    bestSeller: true
  },
  {
    _id:: 31,
    name: "Men's Bomber Jacket",
    description: "Stylish bomber jacket for casual wear.",
    price: 270,
    image: ["image31.jpg"],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "03-12-2024",
    bestSeller: false
  },
  {
    _id:: 32,
    name: "Women's Denim Shorts",
    description: "Trendy denim shorts for a casual summer look.",
    price: 130,
    image: ["image32.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "04-12-2024",
    bestSeller: true
  },
  {
    _id:: 33,
    name: "Men's Athletic Sneakers",
    description: "Comfortable sneakers for running and sports.",
    price: 350,
    image: ["image33.jpg"],
    category: "Men",
    subCategory: "Footwear",
    sizes: ["M", "L", "XL"],
    date: "05-12-2024",
    bestSeller: true
  },
  {
    _id:: 34,
    name: "Women's Running Shoes",
    description: "Lightweight running shoes for athletic performance.",
    price: 340,
    image: ["image34.jpg"],
    category: "Women",
    subCategory: "Footwear",
    sizes: ["S", "M", "L"],
    date: "06-12-2024",
    bestSeller: false
  },
  {
    _id:: 35,
    name: "Men's Leather Wallet",
    description: "Compact and durable leather wallet for everyday use.",
    price: 110,
    image: ["image35.jpg"],
    category: "Men",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "07-12-2024",
    bestSeller: false
  },
  {
    _id:: 36,
    name: "Women's Knit Beanie",
    description: "Warm and cozy knit beanie for winter.",
    price: 60,
    image: ["image36.jpg"],
    category: "Women",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "08-12-2024",
    bestSeller: true
  },
  {
    _id:: 37,
    name: "Men's Cargo Shorts",
    description:
      "Comfortable and practical cargo shorts with multiple pockets.",
    price: 150,
    image: ["image37.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "09-12-2024",
    bestSeller: false
  },
  {
    _id:: 38,
    name: "Women's Button-Down Cardigan",
    description: "Stylish cardigan for a casual and cozy look.",
    price: 220,
    image: ["image38.jpg"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    date: "10-12-2024",
    bestSeller: true
  },
  {
    _id:: 39,
    name: "Men's Wool Sweater",
    description: "Soft and warm wool sweater for winter.",
    price: 280,
    image: ["image39.jpg"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    date: "11-12-2024",
    bestSeller: false
  },
  {
    _id:: 40,
    name: "Women's Leather Boots",
    description: "Stylish and durable leather boots for winter.",
    price: 390,
    image: ["image40.jpg"],
    category: "Women",
    subCategory: "Footwear",
    sizes: ["S", "M", "L"],
    date: "12-12-2024",
    bestSeller: true
  },
  {
    _id:: 41,
    name: "Men's Cotton Trousers",
    description: "Lightweight cotton trousers for a casual look.",
    price: 160,
    image: ["image41.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "13-12-2024",
    bestSeller: true
  },
  {
    _id:: 42,
    name: "Women's Cotton Scarf",
    description: "Soft cotton scarf perfect for any outfit.",
    price: 90,
    image: ["image42.jpg"],
    category: "Women",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "14-12-2024",
    bestSeller: false
  },
  {
    _id:: 43,
    name: "Men's Casual Blazer",
    description: "Sharp casual blazer for a semi-formal look.",
    price: 310,
    image: ["image43.jpg"],
    category: "Men",
    subCategory: "Formalwear",
    sizes: ["M", "L", "XL"],
    date: "15-12-2024",
    bestSeller: true
  },
  {
    _id:: 44,
    name: "Women's Wide Leg Pants",
    description: "Chic wide leg pants for a trendy style.",
    price: 170,
    image: ["image44.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "16-12-2024",
    bestSeller: false
  },
  {
    _id:: 45,
    name: "Men's Running Shorts",
    description: "Breathable shorts designed for running and training.",
    price: 140,
    image: ["image45.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "17-12-2024",
    bestSeller: true
  },
  {
    _id:: 46,
    name: "Women's Evening Gown",
    description: "Elegant evening gown perfect for formal events.",
    price: 450,
    image: ["image46.jpg"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "18-12-2024",
    bestSeller: false
  },
  {
    _id:: 47,
    name: "Men's Leather Belt",
    description: "Classic leather belt for everyday wear.",
    price: 80,
    image: ["image47.jpg"],
    category: "Men",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "19-12-2024",
    bestSeller: true
  },
  {
    _id:: 48,
    name: "Women's Wrap Dress",
    description: "Flattering wrap dress for a chic and versatile style.",
    price: 280,
    image: ["image48.jpg"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "20-12-2024",
    bestSeller: false
  },
  {
    _id:: 49,
    name: "Men's Wool Coat",
    description: "Sophisticated wool coat for a polished look.",
    price: 500,
    image: ["image49.jpg"],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "21-12-2024",
    bestSeller: false
  },
  {
    _id:: 50,
    name: "Women's High Heels",
    description: "Elegant high heels for formal and casual wear.",
    price: 230,
    image: ["image50.jpg"],
    category: "Women",
    subCategory: "Footwear",
    sizes: ["S", "M", "L"],
    date: "22-12-2024",
    bestSeller: true
  }
];
