import { images } from "../assets/Images";

export const product = [
  {
    _id: 1,
    name: "Henley Shirt",
    description:
      "Comfortable cotton top with a round neck design, perfect for casual wear.",
    price: 19,
    OrigionalPrice: 3850,
    image: [images.Henley_T_Shirt_NB_1],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    date: "12-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 2,
    name: "Striped Curved",
    description: "Soft and stylish T-shirt for everyday casual look.",
    price: 150,
    OrigionalPrice: 3850,
    image: [images.Striped_Curved_Hem_T_Shirt_1],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    date: "10-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 4,
    name: "v nick",
    description: "Classic denim jacket with a contemporary twist.",
    price: 18,
    OrigionalPrice: 3850,
    image: [images.V_Neck_T_Shirt_Black_4],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L"],
    date: "07-11-2024",
    bestSeller: false,
    NewArrival: true,
    NewArrival: true
  },
  {
    _id: 5,
    name: "Polo Shirt",
    description: "Elegant flare skirt for a chic look.",
    price: 18,
    OrigionalPrice: 3850,
    image: [images.V_Neck_T_Shirt_DBlack_1],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M"],
    date: "15-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 6,
    name: "V nick T-Shirt",
    description: "Cozy and stylish hoodie for cold weather.",
    price: 220,
    OrigionalPrice: 3850,
    image: [images.Henley_T_Shirt_NB_3],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "18-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 7,
    name: "V nick Shirt",
    description:
      "Comfortable slim fit chinos perfect for work or casual outings.",
    price: 190,
    OrigionalPrice: 3850,
    image: [images.V_Neck_T_Shirt_DBlack_4],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    date: "20-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 8,
    name: "Sky Blue Shirt",
    description: "Warm and comfortable crewneck sweatshirt.",
    price: 160,
    OrigionalPrice: 3850,
    image: [images.V_Neck_T_Shirt_Sky_Blue],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    date: "12-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 9,
    name: "Green Shirt",
    description: "Stretchable and durable leggings for yoga and workout.",
    price: 130,
    OrigionalPrice: 3850,
    image: [images.V_Neck_T_Shirt_Green],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "10-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 10,
    name: "MNDZ Signature Cap - Maroon",
    description: "Stylish full-zip hoodie for casual wear.",
    price: 2499,
    OrigionalPrice: 3850,
    image: [images.Cap_1, images.Cap_2, images.Cap_3],
    category: "Men",
    subCategory: "Headwear",
    sizes: ["M", "L", "XL"],
    date: "25-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 11,
    name: "MNDZ Original Cap - Black",
    description: "Lightweight summer dress perfect for warm weather.",
    price: 2300,
    OrigionalPrice: 3850,
    image: [images.BCap_1, images.BCap_2, images.BCap_3],
    category: "Men",
    subCategory: "Headwear",
    sizes: ["S", "M", "L"],
    date: "22-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 12,
    name: "MNDZ Embro_idered Cap - Khaki",
    description: "Classic polo shirt for formal and casual settings.",
    price: 3000,
    OrigionalPrice: 3850,
    image: [images.YCap_1, images.YCap_2, images.YCap_3],
    category: "Men",
    subCategory: "Headwear",
    sizes: ["M", "L", "XL"],
    date: "12-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 13,
    name: "MNDZ Embroidered Cap - White",
    description: "Loose-fit casual trousers for a comfortable day out.",
    price: 2490,
    OrigionalPrice: 3850,
    image: [images.WCap_1, images.WCap_2, images.WCap_3],
    category: "Men",
    subCategory: "Headwear",
    sizes: ["S", "M", "L", "XL"],
    date: "13-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 14,
    name: "Women's Butterfly Printed Hoodie - Light Purple",
    description:
      "Breathable and comfortable shorts for exercise and casual wear.",
    price: 2090,
    OrigionalPrice: 3850,
    image: [
      images.WomenButterflyPrintedHoodie_1,
      images.WomenButterflyPrintedHoodie_2,
      images.WomenButterflyPrintedHoodie_3
    ],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "17-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 15,
    name: "Women's Polka dot Exclusive Hoodie - Navy",
    description: "Waterproof jacket suitable for rainy weather.",
    price: 3050,
    OrigionalPrice: 3850,
    image: [
      images.WomenPOLKADOTHoodieBlue_1,
      images.WomenPOLKADOTHoodieBlue_2,
      images.WomenPOLKADOTHoodieBlue_3
    ],
    category: "Unisex",
    subCategory: "Outerwear",
    sizes: ["S", "M", "L", "XL"],
    date: "12-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 16,
    name: "Women's High Waist Boot Cut Flare Jeans - Black",
    description: "Stylish long sleeve shirt for casual or formal wear.",
    price: 3500,
    OrigionalPrice: 3850,
    image: [images.JeansBlack_1, images.JeansBlack_2, images.JeansBlack_3],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    date: "21-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 17,
    name: "Women's High Waist Boot Cut Flare Jeans - White",
    description: "Durable leather belt to complement your outfit.",
    price: 3080,
    OrigionalPrice: 3850,
    image: [images.JeansWhite_1, images.JeansWhite_2, images.JeansWhite_3],
    category: "Unisex",
    subCategory: "Accessories",
    sizes: ["M", "L"],
    date: "14-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 18,
    name: "Women's Exclusive Printed Pull Over Fleece Hoodie - Black",
    description: "Supportive and comfortable sports bra for activewear.",
    price: 2999,
    OrigionalPrice: 3850,
    image: [
      images.WomenPrintedFleeceHoodieBlack_1,
      images.WomenPrintedFleeceHoodieBlack_2,
      images.WomenPrintedFleeceHoodieBlack_3
    ],
    category: "Women",
    subCategory: "Innerwear",
    sizes: ["S", "M", "L"],
    date: "12-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 19,
    name: "Women's High Waist Flare Cut Jeans - Black",
    description: "Full tracksuit for athletic or casual wear.",
    price: 3299,
    OrigionalPrice: 3850,
    image: [
      images.WomenHighWaistFlareCutJeansBlack_1,
      images.WomenHighWaistFlareCutJeansBlack_2,
      images.WomenHighWaistFlareCutJeansBlack_3
    ],
    category: "Men",
    subCategory: "Activewear",
    sizes: ["M", "L", "XL"],
    date: "20-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 20,
    name: "Women's Polka dot Exclusive Hoodie - Red",
    description: "Stretchable skinny jeans for a sleek look.",
    price: 3450,
    OrigionalPrice: 3850,
    image: [
      images.WomenPOLKADOTHoodieRED_1,
      images.WomenPOLKADOTHoodieRED_2,
      images.WomenPOLKADOTHoodieRED_3
    ],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "16-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 21,
    name: "Ignite Trouser - Navy",
    description:
      "Kickstart your winters with the stylish Ignite Cardigan. Made from premium material to keep you cozy and comfy from the winter chills!",
    price: 3080,
    OrigionalPrice: 3850,
    image: [
      images.IgniteTrouser_1,
      images.IgniteTrouser_2,
      images.IgniteTrouser_3
    ],
    category: "Unisex",
    subCategory: "Accessories",
    sizes: ["M", "L"],
    date: "14-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 22,
    name: "Women's Workout Leggings",
    description: "High-performance leggings for workouts and yoga.",
    price: 2150,
    OrigionalPrice: 3850,
    image: [
      images.GripCoreLeggingsPink_1,
      images.GripCoreLeggingsPink_2,
      images.GripCoreLeggingsPink_3
    ],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "19-11-2024",
    bestSeller: true,
    NewArrival: true
  },

  {
    _id: 23,
    name: "Girl's Polka dot Exclusive Sweat Shirt - Navy",
    description: "Warm and stylish jacket for cold weather.",
    price: 350,
    OrigionalPrice: 3850,
    image: [images.GirlPOLKADOT_1, images.GirlPOLKADOT_2],
    category: "Kids",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "22-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 24,
    name: "Girl's Polka dot Exclusive Sweat Shirt - Red",
    description: "Cozy fleece jacket for a casual and warm layer.",
    price: 230,
    OrigionalPrice: 3850,
    image: [images.GirlPOLKADOTRED_1, images.GirlPOLKADOTRED_2],
    category: "Women",
    subCategory: "Outerwear",
    sizes: ["S", "M", "L"],
    date: "23-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 25,
    name: "Boy's Hanging With Dad Printed Sweat Shirt - Navy",
    description: "Durable and functional cargo pants with multiple pockets.",
    price: 180,
    OrigionalPrice: 3850,
    image: [
      images.HangingWithDad_1,
      images.HangingWithDad_2,
      images.HangingWithDad_3
    ],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "24-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 26,
    name: "Attractive Printed Kids Unisex Sweat Shirt - Navy",
    description: "Premium leather gloves for a stylish winter accessory.",
    price: 100,
    OrigionalPrice: 3850,
    image: [
      images.AttractivePrintedKid_1,
      images.AttractivePrintedKid_2,
      images.AttractivePrintedKid_3
    ],
    category: "Women",
    subCategory: "Accessories",
    sizes: ["S", "M"],
    date: "25-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 27,
    name: "Fantasy Girl Power TeeDark Green",
    description: "Comfortable sneakers for running and sports.",
    price: 350,
    OrigionalPrice: 3850,
    image: [
      images.FantasyGirlPowerTeeDarkGreen_1,
      images.FantasyGirlPowerTeeDarkGreen_2,
      images.FantasyGirlPowerTeeDarkGreen_3
    ],
    category: "Kids",
    subCategory: "Footwear",
    sizes: ["M", "L", "XL"],
    date: "05-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 28,
    name: "Girl's Allover Floral Printed Fleece Hoodie Twin Set - Navy",
    description: "Flowing maxi dress perfect for formal events.",
    price: 320,
    OrigionalPrice: 3850,
    image: [
      images.GirlAlloverNavy_1,
      images.GirlAlloverNavy_2,
      images.GirlAlloverNavy_3
    ],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "28-11-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 29,
    name: "Girl's Allover Floral Printed Fleece Twin Set - Navy",
    description: "Elegant and formal suit for special occasions.",
    price: 550,
    OrigionalPrice: 3850,
    image: [
      images.GirlAlloverFloralPrintedNavy_1,
      images.GirlAlloverFloralPrintedNavy_2,
      images.GirlAlloverFloralPrintedNavy_3,
      images.GirlAlloverFloralPrintedNavy_4
    ],
    category: "Kids",
    subCategory: "Formalwear",
    sizes: ["M", "L", "XL"],
    date: "30-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 30,
    name: "Exclusive Gold Lion Printed Sweat Shirt - Navy",
    description: "Classic wool coat for stylish winter wear.",
    price: 400,
    OrigionalPrice: 3850,
    image: [
      images.GoldLionPrintedSweatShirtNavy_1,
      images.GoldLionPrintedSweatShirtNavy_2,
      images.GoldLionPrintedSweatShirtNavy_3
    ],
    category: "Kids",
    subCategory: "Outerwear",
    sizes: ["M", "L"],
    date: "01-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 31,
    name: "Marathon Junior Shorts",
    description: "Stylish bomber jacket for casual wear.",
    price: 270,
    OrigionalPrice: 3850,
    image: [
      images.MarathonJuniorShorts_1,
      images.MarathonJuniorShorts_2,
      images.MarathonJuniorShorts_3
    ],
    category: "Kids",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "03-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 32,
    name: "Explorer Fresh Vibes Tee Black Shirt",
    description: "Trendy denim shorts for a casual summer look.",
    price: 3000,
    OrigionalPrice: 3850,
    image: [
      images.ExplorerFreshVibesTeeBlack_1,
      images.ExplorerFreshVibesTeeBlack_2,
      images.ExplorerFreshVibesTeeBlack_3
    ],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "04-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 27,
    name: "Girl's Allover Floral Printed Fleece Twin Set - Red",
    description: "Warm knitted scarf for a cozy winter look.",
    price: 70,
    OrigionalPrice: 3850,
    image: [images.GirlsAlloverRed_1, images.GirlsAlloverRed_2],
    category: "Kids",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "12-11-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 34,
    name: "Women's Running Shoes",
    description: "Lightweight running shoes for athletic performance.",
    price: 340,
    OrigionalPrice: 3850,
    image: ["image34.jpg"],
    category: "Women",
    subCategory: "Footwear",
    sizes: ["S", "M", "L"],
    date: "06-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 35,
    name: "Men's Leather Wallet",
    description: "Compact and durable leather wallet for everyday use.",
    price: 110,
    OrigionalPrice: 3850,
    image: ["image35.jpg"],
    category: "Men",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "07-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 36,
    name: "Women's Knit Beanie",
    description: "Warm and cozy knit beanie for winter.",
    price: 60,
    OrigionalPrice: 3850,
    image: ["image36.jpg"],
    category: "Women",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "08-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 37,
    name: "Men's Cargo Shorts",
    description:
      "Comfortable and practical cargo shorts with multiple pockets.",
    price: 150,
    OrigionalPrice: 3850,
    image: ["image37.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "09-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 38,
    name: "Women's Button-Down Cardigan",
    description: "Stylish cardigan for a casual and cozy look.",
    price: 220,
    OrigionalPrice: 3850,
    image: ["image38.jpg"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    date: "10-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 39,
    name: "Men's Wool Sweater",
    description: "Soft and warm wool sweater for winter.",
    price: 280,
    OrigionalPrice: 3850,
    image: ["image39.jpg"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    date: "11-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 40,
    name: "Women's Leather Boots",
    description: "Stylish and durable leather boots for winter.",
    price: 390,
    OrigionalPrice: 3850,
    image: ["image40.jpg"],
    category: "Women",
    subCategory: "Footwear",
    sizes: ["S", "M", "L"],
    date: "12-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 41,
    name: "Men's Cotton Trousers",
    description: "Lightweight cotton trousers for a casual look.",
    price: 160,
    OrigionalPrice: 3850,
    image: ["image41.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "13-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 42,
    name: "Women's Cotton Scarf",
    description: "Soft cotton scarf perfect for any outfit.",
    price: 90,
    OrigionalPrice: 3850,
    image: ["image42.jpg"],
    category: "Women",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "14-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 43,
    name: "Men's Casual Blazer",
    description: "Sharp casual blazer for a semi-formal look.",
    price: 310,
    OrigionalPrice: 3850,
    image: ["image43.jpg"],
    category: "Men",
    subCategory: "Formalwear",
    sizes: ["M", "L", "XL"],
    date: "15-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 44,
    name: "Women's Wide Leg Pants",
    description: "Chic wide leg pants for a trendy style.",
    price: 170,
    OrigionalPrice: 3850,
    image: ["image44.jpg"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    date: "16-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 45,
    name: "Men's Running Shorts",
    description: "Breathable shorts designed for running and training.",
    price: 140,
    OrigionalPrice: 3850,
    image: ["image45.jpg"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    date: "17-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 46,
    name: "Women's Evening Gown",
    description: "Elegant evening gown perfect for formal events.",
    price: 450,
    OrigionalPrice: 3850,
    image: ["image46.jpg"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "18-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 47,
    name: "Men's Leather Belt",
    description: "Classic leather belt for everyday wear.",
    price: 80,
    OrigionalPrice: 3850,
    image: ["image47.jpg"],
    category: "Men",
    subCategory: "Accessories",
    sizes: ["One Size"],
    date: "19-12-2024",
    bestSeller: true,
    NewArrival: true
  },
  {
    _id: 48,
    name: "Women's Wrap Dress",
    description: "Flattering wrap dress for a chic and versatile style.",
    price: 280,
    OrigionalPrice: 3850,
    image: ["image48.jpg"],
    category: "Women",
    subCategory: "Dresses",
    sizes: ["S", "M", "L"],
    date: "20-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 49,
    name: "Men's Wool Coat",
    description: "Sophisticated wool coat for a polished look.",
    price: 500,
    OrigionalPrice: 3850,
    image: ["image49.jpg"],
    category: "Men",
    subCategory: "Outerwear",
    sizes: ["M", "L", "XL"],
    date: "21-12-2024",
    bestSeller: false,
    NewArrival: true
  },
  {
    _id: 50,
    name: "Women's High Heels",
    description: "Elegant high heels for formal and casual wear.",
    price: 230,
    OrigionalPrice: 3850,
    image: ["image50.jpg"],
    category: "Headwear",
    subCategory: "Footwear",
    sizes: ["S", "M", "L"],
    date: "22-12-2024",
    bestSeller: true,
    NewArrival: true
  }
];
